name: Render Documentation

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/render-documentation.ya?ml"
      - "examples/**"
      - "src/**"
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/render-documentation.ya?ml"
      - "examples/**"
      - "src/**"
  workflow_dispatch:
      
jobs:
  render-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - uses: sebromero/render-docs-github-action@main
      with:
        source-path: './src'
        target-path: './docs/api.md'